config/routes.rb
Rails.application.routes.draw do
  resources :volunteers
  resources :jobs
  resources :profiles
  devise_for :users
  root 'home#page'
  # get 'home/page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  # Volunteers belong to both a profile and a job
  belongs_to :profile
  belongs_to :job
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_action :set_volunteer, only: %i[ show edit update ]

  # GET /volunteers or /volunteers.json
  def index
    @volunteers = Volunteer.all
  end

  # GET /volunteers/1 or /volunteers/1.json
  def show
  end

  # GET /volunteers/new
  def new
    @volunteer = Volunteer.new
  end

  # GET /volunteers/1/edit
  def edit
  end

  # POST /volunteers or /volunteers.json
  def create
    @volunteer = Volunteer.new(volunteer_params)
    respond_to do |format|
      if @volunteer.save
        format.html { redirect_to profile_path(id: current_user.id), notice: "You successfully volunteered for a job!" }
        format.json { render :show, status: :created, location: @volunteer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /volunteers/1 or /volunteers/1.json
  def update
    respond_to do |format|
      if @volunteer.update(volunteer_params)
        format.html { redirect_to @volunteer, notice: "Volunteer was successfully updated." }
        format.json { render :show, status: :ok, location: @volunteer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @volunteer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /volunteers/1 or /volunteers/1.json
  
  # Volunteer is a has many through relationship, and each of its parameters are thus found through volunteer e.g. [:volunteer][:profile_id]
  def destroy
    @volunteer = Volunteer.find_by(profile_id: params[:volunteer][:profile_id], job_id: params[:volunteer][:job_id])
    @volunteer.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(id: current_user.id), notice: "You have successfully left the job." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_volunteer
      @volunteer = Volunteer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def volunteer_params
      params.require(:volunteer).permit(:profile_id, :job_id)
    end
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/volunteers/_form.html.erb
<%= simple_form_for(@volunteer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :profile %>
    <%= f.association :job %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/volunteers/edit.html.erb
<h1>Editing Volunteer</h1>

<%= render 'form', volunteer: @volunteer %>

<%= link_to 'Show', @volunteer %> |
<%= link_to 'Back', volunteers_path %>

app/views/volunteers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Volunteers</h1>

<table>
  <thead>
    <tr>
      <th>Profile</th>
      <th>Job</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @volunteers.each do |volunteer| %>
      <tr>
        <td><%= volunteer.profile_id %></td>
        <td><%= volunteer.job_id %></td>
        <td><%= link_to 'Show', volunteer %></td>
        <td><%= link_to 'Edit', edit_volunteer_path(volunteer) %></td>
        <td><%= link_to 'Destroy', volunteer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Volunteer', new_volunteer_path %>

app/views/volunteers/new.html.erb
<h1>New Volunteer</h1>

<%= render 'form', volunteer: @volunteer %>

<%= link_to 'Back', volunteers_path %>

app/views/volunteers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Profile:</strong>
  <%= @volunteer.profile_id %>
</p>

<p>
  <strong>Job:</strong>
  <%= @volunteer.job_id %>
</p>

<%= link_to 'Edit', edit_volunteer_path(@volunteer) %> |
<%= link_to 'Back', volunteers_path %>