config/routes.rb
Rails.application.routes.draw do
  resources :volunteers
  resources :jobs
  resources :profiles
  devise_for :users
  root 'home#page'
  # get 'home/page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  # Profiles belong to a user who has made an account
  belongs_to :user
  # Profiles can create jobs 
  has_many :jobs_to_create, class_name: "Job", foreign_key: "creator_id"
  # Profiles can volunteer for jobs through the volunteer model
  has_many :volunteers
  has_many :jobs, through: :volunteers  
  # Profiles have one attached picture 
  has_one_attached :picture

  # All profiles must have a valid username
  validates :user_name, length: { in: 2..100 }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  # A profile ID will be the same as the User ID 
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id 

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_path, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :user_name, :github, :bio, :representing_organisation, :user_id, :picture)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :user_name, required: true %>
    <%= f.input :github %>
    <%= f.input :bio %>
    <%= f.input :representing_organisation %>
    <br>
    <p> Profile Picture </p>
    <%= f.file_field :picture, accept: "image/png, image/jpg, image/jpeg"%>
  </div>

  <br>
  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<br>
<%= link_to 'Back', profile_path, class:"btn btn-secondary" %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>User name</th>
      <th>Github</th>
      <th>Bio</th>
      <th>Representing organisation</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.user_name %></td>
        <td><%= profile.github %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.representing_organisation %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>



<div class="card-deck" >

  <div class="card-group">

    <div class="card card border-dark bg-light">
     <h5 class="card-title"></h5>
        <% if @profile.picture.attached? %>
          <%= image_tag @profile.picture, class:"profile-img" %>
        <% end %>
        
    <div class="card-body">
      
    </div>
    
  </div>
  <div class="card card border-dark">
  
    <div class="card-body">
      <h5 class="card-title"><%= @profile.user_name %></h5>
      <p>
      <strong>First name:</strong>
      <%= @profile.first_name %>
      </p>

      <p>
        <strong>Last name:</strong>
        <%= @profile.last_name %>
      </p>


      <p>
      <strong>Representing organisation:</strong>
      <%= @profile.representing_organisation %>
      </p>

      <p>
        <strong>Github:</strong>
        <%= @profile.github %>
      </p>

      
<% if @profile.id == current_user.profile.id%>
<%= link_to 'Edit Profile', edit_profile_path(@profile), class:"btn btn-primary" %> 
<%= link_to 'Create Job', new_job_path, class:"btn btn-success" %>
<% end %>

    </div>
    
  </div>
 
</div>
</div>

    
  

  <div class="card card border-dark mb-3">
    <div class="card-body">
      <h5 class="card-title">Bio</h5>
      <p><%= @profile.bio %></p>
    </div>
  </div>


  <div class="card card border-dark mb-3">
    <div class="card-body">
      <h5 class="card-title">Current Jobs</h5>
      <%  @profile.jobs.all.each do |job| %>
        <% if job.complete == false %>
        <%= link_to job.title, job_path(job) %>
        <% end %>
        <% end %>
    </div>
  </div>

  <div class="card card border-dark mb-3">
    <div class="card-body">
      <h5 class="card-title">Past Jobs</h5>
      <%  @profile.jobs.all.each do |job| %>
        <% if job.complete == true %>
        <%= link_to job.title, job_path(job) %>
        <% end %>
        <% end %>
    </div>
  </div>

</div>