config/routes.rb
Rails.application.routes.draw do
  resources :volunteers
  resources :jobs
  resources :profiles
  devise_for :users
  root 'home#page'
  # get 'home/page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  # Jobs belong to their creator via the class Profile
  belongs_to :creator, class_name: "Profile"
  # Jobs have many profiles through volunteers.
  # If a job is destroyed, then destroy will be called on its associated volunteers.
  has_many :volunteers, dependent: :destroy
  has_many :profiles, through: :volunteers
# All jobs must have a title, and a valid start and end date
  validates :title, length: { in: 2..100 }
  validates_date :start_date, on: :create, on_or_after: :today
  validates_datetime :end_date, after: :start_date 
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all.preload(:profiles)

  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    if user_signed_in?
      if current_user.profile
        @job = Job.new
      else
        redirect_to new_profile_path
      end
    else
      redirect_to new_user_session_path
    end
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  # A jobs creator ID will be the same as the current user's profile ID
  def create
    @job = Job.new(job_params)
    @job.creator_id = current_user.profile.id 

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :description, :start_date, :end_date, :complete, :creator_id, :github, :discord, :trello)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(@job) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, required: true %>
    <%= f.input :description %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    
    <%= f.input :github %>
    <%= f.input :discord %>
    <%= f.input :trello %>
    <p><br>Mark Job As Complete</p>
    <%= f.input :complete %>
  </div>

  <div class="form-actions">
  <br>
    <%= f.button :submit, class:"btn btn-success" %>
  </div>

  

<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Destroy', @job, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Open Jobs</h1>
<br>
<% # Link to new job form %>
<%= link_to 'New Job', new_job_path, class:"btn btn-success" %>
<table class="table table-striped">
  <thead>
    <tr>
    <th>Creator</th>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Developers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% # List all open jobs with relevant information such as creator and quantity of volunteers. Eager loading used for job.profiles.count %>
  <tbody>
    <% @jobs.each do |job| %>
      
      <tr>
      <% if job.complete == false %>
        <td><%= link_to job.creator.user_name, profile_path(id: job.creator.id)  %></td>
        <td><%= link_to job.title, job %></td>
        <td><%= job.description %></td>
        <td><%= job.start_date %></td>
        <td><%= job.end_date %></td>
        <td><%= job.profiles.count %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card border-dark mb-3" style="max-width: 40rem;">
  <div class="card-header card-title">
  <% if @job.complete %>
    Past Job
    <% else %>

    Open Job
    <% end %>
  </div>
  <div class="card-body text-dark">
    <h5 class="card-title"><%= @job.title %></h5>
<% # Each job should have a link to their creator's profile %>
    <p>
      <strong>Creator:</strong>
      <%= link_to @job.creator.user_name, profile_path(id: @job.creator.id)  %>
    </p>

    <p>
      <strong>Start date:</strong>
      <%= @job.start_date %>
    </p>

    <p>
      <strong>End date:</strong>
      <%= @job.end_date %>
    </p>
    <% # All volunteers on a project should be listed with a link to their profile %>
    <p>
      <strong>Developers:</strong>
      <%  @job.profiles.all.each do |profile| %>
        <%= link_to profile.user_name, profile_path(id: profile)  %>
        <% end %>
        
    </p>

    <p>
      <strong>Github:</strong>
      <%= @job.github %>
    </p>

    <p>
      <strong>Discord:</strong>
      <%= @job.discord %>
    </p>

    <p>
      <strong>Trello:</strong>
      <%= @job.trello %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @job.description %>
    </p>
  </div>
</div>

<% # If the job has been complete then users should not see the volunteer button %>
<% if @job.complete %>
  This job has been completed
<% else %>
<% begin %>
  <% job = current_user.profile.jobs.find(@job.id) %>
  <%= link_to 'Leave Job', volunteer_path(volunteer: {profile_id: current_user.profile.id, job_id: @job.id}), method: :delete, class:"btn btn-success" %> 
  <% rescue %>
  <%= link_to 'Volunteer', volunteers_path(volunteer: {profile_id: current_user.profile.id, job_id: @job.id}), method: :post, class:"btn btn-success" %>
  <% end %>
<% end %>

<% # Only the job's creator should see the edit job button %>
<% if @job.creator_id == current_user.profile.id%>
  <%= link_to 'Edit Job', edit_job_path(@job), class:"btn btn-success" %> 
<% end %>